=== Inf22tig13/AnimaisRepositorio/XML/animais.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.animais.org" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="categoria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="gatos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="gato" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nome"/>
                    <xs:element type="xs:string" name="idade"/>
                    <xs:element type="xs:string" name="raca"/>
                    <xs:element type="xs:string" name="genero"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="caes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cao" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nome"/>
                    <xs:element type="xs:string" name="idade"/>
                    <xs:element type="xs:string" name="raca"/>
                    <xs:element type="xs:string" name="genero"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Inf22tig13/AnimaisRepositorio/XML/animais.xml
<?xml version="1.0" encoding="UTF-8"?>
<categoria xmlns="http://www.animais.org"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.animais.org animais.xsd">
  <gatos>
    <gato>
      <nome>Miau</nome>
      <idade>4 anos</idade>
      <raca>Persa</raca>
      <genero>Femea</genero>
    </gato>
    <gato>
      <nome>Pocoio</nome>
      <idade>6 meses</idade>
      <raca>Van Turco</raca>
      <genero>Macho</genero>
    </gato>
    <gato>
      <nome>Chentric</nome>
      <idade>8 anos</idade>
      <raca>Snorlax</raca>
      <genero>Macho</genero>
    </gato>
    <gato>
      <nome>Luninho</nome>
      <idade>6 anos</idade>
      <raca>Rafeiro</raca>
      <genero>Macho</genero>
    </gato>
    <gato>
      <nome>Milos</nome>
      <idade>12 anos</idade>
      <raca>Persa Branco</raca>
      <genero>Macho</genero>
    </gato>
    <gato>
      <nome>Roberto</nome>
      <idade>14 anos</idade>
      <raca>Rafeiro</raca>
      <genero>Macho</genero>
    </gato>
  </gatos>
  <caes>
    <cao>
      <nome>Boltz</nome>
      <idade>2 anos</idade>
      <raca>Labrador Retriever</raca>
      <genero>Macho</genero>
    </cao>
    <cao>
      <nome>Raivado</nome>
      <idade>3 meses</idade>
      <raca>Pitbull</raca>
      <genero>Macho</genero>
    </cao>
    <cao>
      <nome>Raby</nome>
      <idade>7 anos</idade>
      <raca>Pondengo</raca>
      <genero>Macho</genero>
    </cao>
    <cao>
      <nome>Pipoca</nome>
      <idade>2 anos</idade>
      <raca>Salsicha</raca>
      <genero>Femea</genero>
    </cao>
    <cao>
      <nome>Joaquim</nome>
      <idade>15 anos</idade>
      <raca>Perniet da Anatartida</raca>
      <genero>Macho</genero>
    </cao>
    <cao>
      <nome>Opio</nome>
      <idade>11 anos</idade>
      <raca>Pastor Alem√£o</raca>
      <genero>Macho</genero>
    </cao>
  </caes>
</categoria>
